### ISSUE TITLE
exception trying to delete files 

### ISSUE THREAD

**Issue by afmcc** [tesujimath/filebutler#1]
groot$ filebutler
fb:  info -d my-old-ztmp -size +10G
total   545G in        41 files
Endophyte_AR3060_AR3018_RNA-seq   221G in        18 files
GBS_ASW   140G in        11 files
GBS_WhiteClover_GeneticGain    68G in         6 files
Lamb_rumen_amplicons_T252    66G in         2 files
GBS_Rye    24G in         2 files
AH_rat_feeding_trial    23G in         2 files

fb:  delete my-old-ztmp -size +10G
Traceback (most recent call last):
  File "/stash/miniconda3/envs/universal3/bin/filebutler", line 6, in <module>
    sys.exit(filebutler.__main__.main())
  File "/stash/miniconda3/envs/universal3/lib/python3.6/site-packages/filebutler/__main__.py", line 51, in main
    cli.interact()
  File "/stash/miniconda3/envs/universal3/lib/python3.6/site-packages/filebutler/CLI.py", line 233, in interact
    done = self._handleProcess(line)
  File "/stash/miniconda3/envs/universal3/lib/python3.6/site-packages/filebutler/CLI.py", line 207, in _handleProcess
    done = self._process(line)
  File "/stash/miniconda3/envs/universal3/lib/python3.6/site-packages/filebutler/CLI.py", line 194, in _process
    method(toks, usage)
  File "/stash/miniconda3/envs/universal3/lib/python3.6/site-packages/filebutler/CLI.py", line 415, in _deleteCmd
    os.utime(path, (mtime, mtime))
PermissionError: [Errno 1] Operation not permitted

**Comment by tesujimath** [comment]
Thanks for the bug report.  Fixed in release v0.17.3.
